POST http://localhost:8080/users/register
Content-Type: application/json

{
    "email": "admin@email.com",
    "name": "admin",
    "password": "Rc123456!" 
}



###
POST http://localhost:8080/users/login
Content-Type: application/json

{
    "email": "admin@email.com",
    "password": "Rc123456"
}

###
POST http://localhost:8080/users/tokenValidate
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im9yeWFuQGdtYWlsLmNvbSIsInBhc3N3b3JkIjoib3J5YW4iLCJpYXQiOjE2MzgyODkxNDEsImV4cCI6MTYzODI4OTIwMX0.gg-47xL9rgUOzCVnn3QOfzM6k53JoHDjl3sOyo1ZR04

{
}

###
GET http://localhost:8080/api/v1/information
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGVtYWlsLmNvbSIsInBhc3N3b3JkIjoiUmMxMjM0NTYiLCJpYXQiOjE2MzgzNTY1MzMsImV4cCI6MTYzODM1NjU0M30.vqonUNfBr_da1AFTe4vMIwHGV-caLAIwcSyrWE105co

{
}

###
POST http://localhost:8080/users/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im9yeWFuQGdtYWlsLmNvbSIsInBhc3N3b3JkIjoib3J5YW4iLCJpYXQiOjE2MzgyOTMwMzh9.koFowiXrogw15wjJ60NObwHatTUSkEpBG2UUWkOKIHI"
}

###
POST http://localhost:8080/users/logout
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im9yeWFuQGdtYWlsLmNvbSIsInBhc3N3b3JkIjoib3J5YW4iLCJpYXQiOjE2MzgyOTMyNzB9.Sx6m5BY_9AhHCLhWM8LfG6sAZqEgsVvKm50kVnJjOHc"
}

###
GET http://localhost:8080/api/v1/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGVtYWlsLmNvbSIsInBhc3N3b3JkIjoiUmMxMjM0NTYiLCJpYXQiOjE2MzgzNTUxMjksImV4cCI6MTYzODM1NTEzOX0.SmQgy1rhh6PRCf6xjQaI_BYOe3cS8pxedkzNjaUtiXA

{
}

###
OPTIONS  http://localhost:3000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im9yeWFuQGdtYWlsLmNvbSIsInBhc3N3b3JkIjoib3J5YW4iLCJpYXQiOjE2MzgyOTUwNDIsImV4cCI6MTYzODI5NTEwMn0.fpgfY6zCNKhYbTP0KBHfnHnrxlDOUrt5mcIQEGsFUN0

{
}
